ARG APACHE_VERSION

FROM php:$APACHE_VERSION-apache

ARG APACHE_DOCUMENT_ROOT
ENV APACHE_DOCUMENT_ROOT=$APACHE_DOCUMENT_ROOT

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
