version: "3.9"

services:
  traefik:
    container_name: "${PREFIX}-traefik"
    image: traefik:v2.9.6
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: |-
      --providers.docker.network="${PREFIX}-network"
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.entrypoints: https
      traefik.http.routers.traefik.rule: "Host(`traefik.${DOCKER_DOMAIN}`)"
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.tls: true
      traefik.http.services.traefik.loadbalancer.server.port: 8080
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/config.yml:/etc/traefik/config.yml
      - ./traefik/log:/log
      - ./certs:/etc/certs

  portainer:
    container_name: "${PREFIX}-portainer"
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    command: --logo "${LOGO_URL}"
    volumes:
      - ./portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: true
      traefik.http.routers.portainer.entrypoints: https
      traefik.http.routers.portainer.rule: "Host(`portainer.${DOCKER_DOMAIN}`)"
      traefik.http.routers.portainer.tls: true
      traefik.http.services.portainer.loadbalancer.server.port: 9000

  mailhog:
    image: mailhog:local
    build: https://github.com/mailhog/MailHog.git
    container_name: "${PREFIX}-mailhog"
    ports:
      - "1025:1025"
    labels:
      traefik.enable: true
      traefik.http.routers.mailhog.entrypoints: https
      traefik.http.routers.mailhog.rule: "Host(`mailhog.${DOCKER_DOMAIN}`)"
      traefik.http.routers.mailhog.tls: true
      traefik.http.services.mailhog.loadbalancer.server.port: 8025

networks:
  default:
    name: "${PREFIX}-network"
    external: false
