version: '3.5'

services:
  app:
    container_name: ${PROJECT_NAME}-web
    build:
      context: '.'
      args:
        uid: ${UID}
    restart: always
    command: php -S 0.0.0.0:80 /app/public/index.php
    volumes:
      - ../:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}-web.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}-web.rule=Host(`${PROJECT_NAME}.d.test`)"
      - "traefik.http.routers.${PROJECT_NAME}-web.tls=true"
      - "traefik.http.services.${PROJECT_NAME}-web.loadbalancer.server.port=80"
    networks:
      - default
      - dev-in-docker-network

  # composer:
  #   container_name: ${PROJECT_NAME}-composer
  #   image: composer
  #   command: |-
  #     --interactive
  #     --tty
  #     composer install
  #   volumes:
  #     - ../:/app
  #   networks:
  #     - default

networks:
  default:
    internal: true
  dev-in-docker-network:
    name: dev-in-docker-network
    external: true
