version: '3.5'

services:
  app:
    container_name: ${PROJECT_NAME}-web
    image: php:7.4
    restart: always
    command: php -S 0.0.0.0:80 -t /app/public/
    volumes:
      - ../:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}-web.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}-web.rule=Host(`${PROJECT_NAME}.d.test`)"
      - "traefik.http.routers.${PROJECT_NAME}-web.tls=true"
      - "traefik.http.services.${PROJECT_NAME}-web.loadbalancer.server.port=80"
    networks:
      - default
      - dev-in-docker-network

networks:
  default:
    internal: true
  dev-in-docker-network:
    name: dev-in-docker-network
    external: true
